const venues = {
    acuppellacafe: "Acuppella Cafe",
    ambergis: "Ambergis Café",
    amcentralbloc: "Ayala Malls Central Bloc",
    amcircuit: "Ayala Malls Circuit",
    amfairviewterraces: "Ayala Malls Fairview Terraces",
    amfeliz: "Ayala Malls Feliz",
    amharborpoint: "Ayala Malls Harbor Point",
    ammanilabay: "Ayala Malls Manila Bay",
    amsolenad: "Ayala Malls Solenad",
    amthe30th: "Ayala Malls The 30th",
    araneta: "Smart Araneta Coliseum",
    aromata: "Aromata Restaurant and Bar",
    auslquadrangle: "AUSL Quadrangle",
    ayalamuseum: "Ayala Museum",
    baguioconvention: "Baguio Convention Center",
    balatasdevcomplex: "Balatas Development Complex",
    bar360: "Bar 360",
    bistro: "The 70's Bistro",
    bossbar: "Boss Bar",
    bridgetowne: "Bridgetowne Open Grounds",
    cafelupe: "Cafe Lupe",
    cantobogchi: "Canto Bogchi Joint",
    ccpgrounds: "CCP Open Grounds",
    centralcraftbalanga: "The Central Craft Beer, Bataan",
    cityboymain: "Cityboy Brew Main",
    citydimare: "City Di Mare",
    clubhype: "Club Hype, Quezon City",
    cornerstonestudio: "Cornerstone Studio",
    covemanila: "Cove Manila",
    cozycove: "The Cozy Cove",
    cprauditorium: "Carlos P. Romulo Auditorium",
    crocodilepark: "Crocodile Park Concert Grounds",
    dinalan: "Dinalan Coffee",
    dininghall: "Dining Hall, Quezon City",
    districtone: "District One",
    diwangtarlac: "Diwa Ng Tarlac Convention Center",
    eastside: "Eastside Events Place",
    eightyeight: "88 FRYER",
    elcalle: "El Calle Food and Music Hall",
    etoncentris: "Eton Centris",
    fblevents: "FBL Events Place",
    festivalmall: "Festival Mall",
    filinvestgrounds: "Filinvest City Events Grounds",
    filinvesttent: "The Filinvest Tent",
    fmmalabon: "Fisher Mall Malabon",
    fpjarena: "FPJ Arena",
    frontier: "New Frontier Theater",
    galleria: "Robinsons Galleria",
    gighouse: "Gighouse",
    grimaldirestobar: "Grimaldi Restobar",
    hangoutresto: "Hangout Resto",
    hardrockmnl: "Hard Rock Café Manila",
    iloiloconvention: "Iloilo Convention Center",
    imajin: "Imajin Arts & Music",
    jessnpats: "Jess & Pat's",
    junction: "Junction 88 Restaurant & Music",
    justinbella: "Justin Bella Alonte Photography Studio",
    kalmabar: "Kalma Bar & Grill",
    kartilya: "Kartilya ng Katipunan",
    landos: "Lando's",
    lyceumdavao: "Lyceum of the Philippines Davao",
    malaboncitisquare: "Malabon Citisquare Mall",
    marianauditorium: "Marian Auditorium, Miriam College",
    marketmarket: "Market! Market!",
    marqueemall: "MarQuee Mall",
    metrotent: "Metrotent Convention Center",
    metrowalk: "Metrowalk Ortigas",
    midastent: "Midas Tent",
    milenya: "Milenya PH",
    minsanstudio: "Minsan Studio",
    moaarena: "SM Mall of Asia Arena",
    moagrounds: "SM Mall of Asia Concert Grounds",
    motorista: "Motorista Bar",
    mows: "Mow's",
    mplazanaga: "M Plaza, Naga",
    musicmuseum: "Music Museum",
    natlteachers: "National Teachers College",
    neutralgroundbar: "Neutral Ground Bar + Kitchen",
    newport: "Newport Performing Arts Theater",
    nineteeneast: "19 East",
    ninoystadium: "Ninoy Aquino Stadium",
    oddcafe: "Odd Café",
    olpubtavern: "Ol' Pub Tavern Restobar",
    oneayala: "One Ayala",
    onetwothree: "123 Block",
    padrino: "Padrino Celebration Pub",
    paoaydunes: "Paoay Sand Dunes",
    paperlantern: "Paper Lantern",
    paseostarosa: "Paseo De Sta. Rosa",
    pharena: "Philippine Arena",
    piccplenary: "PICC Plenary Hall",
    podiumhall: "The Podium Hall",
    poropoint: "Poro Point, La Union",
    puregoldqi: "Puregold QI Central",
    qmc: "Quezon Memorial Circle",
    rabbithole: "Rabbit Hole",
    redrhino: "Red Rhino",
    rmiligan: "Robinsons Iligan",
    rmilocos: "Robinsons Ilocos",
    rmgalleria: "Robinsons Galleria",
    rmgalleriasouth: "Robinsons Galleria South",
    rmmanila: "Robinsons Manila",
    saguijo: "saGuijo Cafe + Bar",
    samsunghall: "Samsung Hall",
    samsungperforming: "Samsung Performing Arts Theater",
    sarisari: "Sari-Sari Cocktails",
    seasidecebugrounds: "SM Seaside Cebu Concert Grounds",
    shangrilaplaza: "Shangri-La Plaza",
    sidequest: "SideQuest: Cafe + Hobby Lounge",
    skydome: "SM North EDSA Skydome",
    smbacolod: "SM City Bacolod",
    smiloilo: "SM City Iloilo",
    smlaspinas: "SM Center Las Piñas",
    smmakati: "SM Makati",
    smmoa: "SM Mall of Asia",
    smnorthedsa: "SM North EDSA",
    smpampanga: "SM City Pampanga",
    smstamesa: "SM City Sta. Mesa",
    smvalenzuela: "SM Valenzuela",
    smxbacolod: "SMX Convention Center Bacolod",
    smxdavao: "SMX Convention Center Davao",
    smxmanila: "SMX Convention Center Manila",
    spaceoneayala: "SPACE at One Ayala",
    takeover: "Takeover Lounge Bar",
    tba: "TBA",
    teatrino: "Teatrino",
    tedellis: "Ted Ellis",
    theatresolaire: "The Theatre at Solaire",
    trinoma: "Trinoma",
    turningtides: "Turning Tides",
    twelvemonkeys: "12 Monkeys",
    unibaguiogym: "University of Baguio Gym",
    unitycoffee: "Unity Coffee and Vinyl",
    unknownpub: "Unknown13 Pub",
    upfilm: "UP Film Center",
    upsunken: "UP Sunken Garden",
    uptechnohub: "U.P. Technohub",
    uptheatre: "UP Theatre",
    venicepiazza: "Venice Piazza, McKinley Hill",
    vivacafe: "Viva Café",
    vmnomo: "NOMO",
    vmtaguig: "Vista Mall Taguig",
    waterfronthotel: "Waterfront Hotel & Casino",
    whimsygame: "Whimsy Game Cafe",
    worldtrade: "World Trade Center",
    xylo: "Xylo at The Palace",
    none: "",
}

const eventType = {
    comedy: "Comedy",
    concert: "Concert",
    fanmeet: "Fan Meet",
    gig: "Gig",
    mall: "Mall Show",
    none: "",
    other: "Other",
};