const venues = {
    ambergis: "Ambergis Café",
    amcentralbloc: "Ayala Malls Central Bloc",
    amfeliz: "Ayala Malls Feliz",
    amharborpoint: "Ayala Malls Harbor Point",
    ammanilabay: "Ayala Malls Manila Bay",
    amthe30th: "Ayala Malls The 30th",
    araneta: "Smart Araneta Coliseum",
    auslquadrangle: "AUSL Quadrangle",
    baguioconvention: "Baguio Convention Center",
    bar360: "Bar 360",
    bistro: "The 70's Bistro",
    bossbar: "Boss Bar",
    bridgetowne: "Bridgetowne, Pasig",
    centralcraftbalanga: "The Central Craft Beer, Bataan",
    cityboymain: "Cityboy Brew Main",
    citydimare: "City Di Mare",
    covemanila: "Cove Manila",
    cozycove: "The Cozy Cove",
    crocodilepark: "Crocodile Park Concert Grounds",
    dinalan: "Dinalan Coffee",
    dininghall: "Dining Hall, Quezon City",
    districtone: "District One",
    diwangtarlac: "Diwa Ng Tarlac Convention Center",
    eastside: "Eastside Events Place",
    eightyeight: "88 FRYER",
    etoncentris: "Eton Centris",
    festivalmall: "Festival Mall",
    fpjarena: "FPJ Arena",
    frontier: "New Frontier Theater",
    galleria: "Robinsons Galleria",
    gighouse: "Gighouse",
    hangoutresto: "Hangout Resto",
    hardrockmnl: "Hard Rock Café Manila",
    iloiloconvention: "Iloilo Convention Center",
    imajin: "Imajin Arts & Music",
    jessnpats: "Jess & Pat's",
    junction: "Junction 88 Restaurant & Music",
    kalmabar: "Kalma Bar & Grill",
    landos: "Lando's",
    malaboncitisquare: "Malabon Citisquare Mall",
    marianauditorium: "Marian Auditorium, Miriam College",
    marketmarket: "Market! Market!",
    marqueemall: "MarQuee Mall",
    metrotent: "Metrotent Convention Center",
    midastent: "Midas Tent, Midas Hotel and Casino",
    milenya: "Milenya PH",
    moaarena: "SM Mall of Asia Arena",
    mows: "Mow's",
    musicmuseum: "Music Museum",
    natlteachers: "National Teachers College",
    newport: "Newport Performing Arts Theater",
    nineteeneast: "19 East",
    onetwothree: "123 Block",
    padrino: "Padrino Celebration Pub",
    pharena: "Philippine Arena",
    piccplenary: "PICC Plenary Hall",
    podiumhall: "The Podium Hall",
    rabbithole: "Rabbit Hole",
    redrhino: "Red Rhino",
    rmiligan: "Robinsons Iligan",
    rmilocos: "Robinsons Ilocos",
    rmgalleria: "Robinsons Galleria",
    rmgalleriasouth: "Robinsons Galleria South",
    samsunghall: "Samsung Hall",
    sarisari: "Sari-Sari Cocktails",
    seasidecebugrounds: "SM Seaside Cebu Concert Grounds",
    skydome: "SM North EDSA Skydome",
    smlaspinas: "SM Center Las Piñas",
    smstamesa: "SM City Sta. Mesa",
    smxbacolod: "SMX Convention Center Bacolod",
    smxdavao: "SMX Convention Center Davao",
    smxmanila: "SMX Convention Center Manila",
    saguijo: "saGuijo Cafe + Bar Events",
    takeover: "Takeover Lounge Bar",
    tba: "TBA",
    tedellis: "Ted Ellis",
    theatresolaire: "The Theatre at Solaire",
    twelvemonkeys: "12 Monkeys",
    unibaguiogym: "University of Baguio Gym",
    unknownpub: "Unknown13 Pub",
    upsunken: "UP Sunken Garden",
    uptechnohub: "U.P. Technohub",
    vivacafe: "Viva Café",
    vmtaguig: "Vista Mall Taguig",
    waterfronthotel: "Waterfront Hotel & Casino",
    worldtrade: "World Trade Center",
}