const venues = {
    ambergis: "Ambergis Café",
    ammanilabay: "Ayala Malls Manila Bay",
    araneta: "Smart Araneta Coliseum",
    auslquadrangle: "AUSL Quadrangle",
    bar360: "Bar 360",
    bistro: "The 70's Bistro",
    bossbar: "Boss Bar",
    bridgetowne: "Bridgetowne, Pasig",
    centralcraftbalanga: "The Central Craft Beer, Bataan",
    cityboymain: "Cityboy Brew Main",
    citydimare: "City Di Mare",
    cozycove: "The Cozy Cove",
    dinalan: "Dinalan Coffee",
    dininghall: "Dining Hall, Quezon City",
    districtone: "District One",
    diwangtarlac: "Diwa Ng Tarlac Convention Center",
    eastside: "Eastside Events Place",
    eightyeight: "88 FRYER",
    etoncentris: "Eton Centris",
    festivalmall: "Festival Mall",
    frontier: "New Frontier Theater",
    galleria: "Robinsons Galleria",
    gighouse: "Gighouse",
    hangoutresto: "Hangout Resto",
    hardrockmnl: "Hard Rock Café Manila",
    imajin: "Imajin Arts & Music",
    junction: "Junction 88 Restaurant & Music",
    kalmabar: "Kalma Bar & Grill",
    landos: "Lando's",
    malaboncitisquare: "Malabon Citisquare Mall",
    marianauditorium: "Marian Auditorium, Miriam College",
    marketmarket: "Market! Market!",
    metrotent: "Metrotent Convention Center",
    milenya: "Milenya PH",
    moaarena: "SM Mall of Asia Arena",
    mows: "Mow's",
    musicmuseum: "Music Museum",
    natlteachers: "National Teachers College",
    newport: "Newport Performing Arts Theater",
    nineteeneast: "19 East",
    onetwothree: "123 Block",
    padrino: "Padrino Celebration Pub",
    pharena: "Philippine Arena",
    piccplenary: "PICC Plenary Hall",
    rabbithole: "Rabbit Hole",
    redrhino: "Red Rhino",
    rmiligan: "Robinsons Iligan",
    rmilocos: "Robinsons Ilocos",
    rmgalleria: "Robinsons Galleria",
    rmgalleriasouth: "Robinsons Galleria South",
    samsunghall: "Samsung Hall",
    sarisari: "Sari-Sari Cocktails",
    skydome: "SM North EDSA Skydome",
    smlaspinas: "SM Center Las Piñas",
    smstamesa: "SM City Sta. Mesa",
    smxbacolod: "SMX Convention Center Bacolod",
    smxdavao: "SMX Convention Center Davao",
    smxmanila: "SMX Convention Center Manila",
    saguijo: "saGuijo Cafe + Bar Events",
    takeover: "Takeover Lounge Bar",
    tba: "TBA",
    tedellis: "Ted Ellis",
    theatresolaire: "The Theatre at Solaire",
    twelvemonkeys: "12 Monkeys",
    unknownpub: "Unknown13 Pub",
    upsunken: "UP Sunken Garden",
    vivacafe: "Viva Café",
    vmtaguig: "Vista Mall Taguig",
    worldtrade: "World Trade Center",
}